services:
  - type: web
    name: manufacturing-crm-server
    env: node
    region: oregon
    plan: free
    branch: main
    rootDir: server
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: NODE_ENV
        value: production
    autoDeploy: true
